# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'arena-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for arena-app
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'
end
